### ISSUE TITLE
Research GraphQL

### ISSUE THREAD

**Issue by bookstein** [bookstein/learning_grid#1]
We need to know if GraphQL would be a good tool for our backend.

Considerations:
- [ ] what is our data model? did we draw it?
- [ ] how and where can we host it? (Heroku, Amazon, Github, etc) We don't want deployment to be a blocker. Who supports GraphQL?
- [ ] What format does the data need to be in (for GraphQL and for React)? See Issue #2 

If we can't figure this out by the next time we pair, we will discard it.

**Comment by bookstein** [comment]
Data model:
- Users
- Zones
- Entries
- Resources

Users have entries
Entries have resources
User-Entry Zone association table? (map User-Entries to Zones)

**Comment by bookstein** [comment]
@keighty

**Comment by keighty** [comment]
Well! Looks like we will need a datastore like mongodb after all! I have found a few resources that I think are quite helpful:
- [GraphQL server](https://github.com/RisingStack/graphql-server)
- [GraphQL getting started](https://blog.risingstack.com/graphql-overview-getting-started-with-graphql-and-nodejs/)
- [GraphQL introduction](https://facebook.github.io/react/blog/2015/05/01/graphql-introduction.html)
- [Introducing Relay and GraphQL](https://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql.html)
- [The GraphQL Spec](https://github.com/facebook/graphql)

Looks like it isn't at a full release yet, so we should make our queries very very simple to avoid breaking changes at 1.0

**Comment by bookstein** [comment]
Nice research @keighty !

Ha - just noticed that the Relay and GraphQL blog post (https://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql.html) was written by a former coworker of mine from Causes.com, Greg Hurrell! Small world. Maybe I can get the inside scoop from him.

Seems like there are many examples showing GraphQL in use with a Node.js server -- so if we did go ahead with the [GraphQL server](https://github.com/RisingStack/graphql-server), we'd probably be in good company as far as online support.

Relay is an interesting story. Sounds like it's meant to help "batch" GraphQL requests, which might be overkill for us. This article says that GraphQL can be used without Relay: http://thenewstack.io/react-with-graphql-for-architecting-apps/

> > While GraphQL will have great first level support for Relay upon its official release, GraphQL will also work well as a stand-alone piece of technology.

I don't know much about MongoDB -- what would you think about using MySQL or Postgres? or is there a specific reason you'd prefer to use Mongo, besides the fact that the GraphQL server (your link) is using it? If so, then I'm in!

**Comment by keighty** [comment]
I think we can use sqllite as a datastore -- I misunderstood and believed that we needed a json datastore to go with the API:

https://www.reindex.io/blog/building-a-graphql-server-with-node-js-and-sql/

ONWARDS!

**Comment by bookstein** [comment]
YAY!

So it sounds like our stack is Node.js, SQLlite3, GraphQL, and React??
